{
    "name": "Factura Electrónica Paraguay (FCWS)",
    "summary": "Integración con el Facturador Electrónico FCWS - SIFEN Paraguay",
    "version": "15.0.2.0.0",
    "category": "Accounting/Localizations",
    "author": "Ruben Recalde, Criterium S.A.",
    "website": "https://www.criterium.com.py",
    'depends': ['base', 'base_vat', 'account', 'account_debit_note', 'l10n_latam_base', 'base_address_extended', 'base_address_city', 'mail', 'py_ctrm_base'],
    "data": [
        "data/account_move_cron.xml",
        "data/fcw_clean_old_cron.xml",
        "data/l10n_latam_identification_type.xml",
        "data/res_country_sifen_data.xml",
        "data/res.country.state.csv",
        "data/res.country.district.csv",
        "data/res.city.csv",
        "security/ir.model.access.csv",
        "views/account_journal_views.xml",
        "wizards/fcws_cancel_wizard.xml",
        "views/account_move_views.xml",
        "views/fcws_document_views.xml",
        "views/l10n_latam_identification_type_views.xml",
        "views/res_company_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_country_views.xml",
        "views/res_district_views.xml",
        "views/res_partner_views.xml",
        "reports/config_report.xml",
        "reports/electronic_billing.xml",
        "wizards/account_move_reversal.xml",
        "wizards/account_debit_note_views.xml",
        "views/mail_template_views.xml",
        "views/fcws_inutilization_views.xml",

    ],

    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
