from . import account_payment_receiptbook
from . import account_payment
from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment_paraguay
from . import account_checkbooks
from . import account_chekbooks_deposit
from . import res_company
from . import res_config_settings
