# -*- coding: utf-8 -*-

{
    'name': 'Modulo de Pagos',
    'version': '14.0.0.1',
    'category': 'Reporting',
    'summary': 'Modulo de Pagos con localización Paraguaya',
    'sequence': '10',
    'author': 'Hugo Benegas, Criterium SA',
    'company': 'Criterium SA',
    'maintainer': 'Hugo Benegas',
    'support': 'hugo.benegas@criterium.com.py',
    'website': 'https://www.criterium.com.py/',
    'demo': [],
    'depends': ['base', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence.xml',
        'reports/orden_pago.xml',
        'reports/listado_cheques.xml',
        'reports/deposito_cheque.xml',
        'reports/config_report.xml',
        'wizard/check_list_report.xml',
        'views/account_move.xml',
        'views/account_journal.xml',
        'views/account_payment.xml',
        'views/account_move_line.xml',
        'views/account_checkbooks.xml',
        'views/account_payment_paraguay.xml',
        'views/res_config_settings_views.xml',
        'views/account_checkbooks_deposit.xml',
        'views/account_payment_receiptbook_view.xml',
        # 'views/text.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
